# Generated by Django 5.1.5 on 2025-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_codechallenge_explanation'),
    ]

    operations = [
    migrations.CreateModel(
        name='GuestUser',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=100, unique=True)), # NAME IS UNIQUE HERE
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
    ),
]
