# Generated by Django 5.1.5 on 2025-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='code',
            field=models.CharField(default='3ba24030', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
