# Generated by Django 5.1.5 on 2025-05-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guestuser_code_alter_guestuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
