# Generated by Django 5.1.5 on 2025-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guestuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='code',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
