# Generated by Django 5.1.5 on 2025-06-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_guestuser_code_alter_guestuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='code',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='created_at',
        ),
    ]
