# Generated by Django 5.1.5 on 2025-06-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_guestuser_code_remove_guestuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='current_challenge',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='magic_word',
            field=models.CharField(default='magicword', max_length=100),
            preserve_default=False,
        ),
    ]
