# Generated by Django 5.1.5 on 2025-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_guestuser_current_challenge_guestuser_magic_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechallenge',
            name='code_template',
        ),
        migrations.RemoveField(
            model_name='codechallenge',
            name='correct_answers_list',
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='starter_code',
            field=models.TextField(default=1, help_text='The starting code provided to the user. They will edit this to create their solution.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='test_cases',
            field=models.TextField(default=1, help_text="Python code with assert statements to validate the user's solution."),
            preserve_default=False,
        ),
    ]
