# Generated by Django 5.1.5 on 2025-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_codechallenge_code_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechallenge',
            name='starter_code',
        ),
        migrations.RemoveField(
            model_name='codechallenge',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='correct_answers_list',
            field=models.JSONField(default=list, help_text='A JSON list of strings representing the exact correct answers for the blanks, IN ORDER.'),
        ),
    ]
