# Generated by Django 5.1.5 on 2025-06-25 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_codechallenge_starter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechallenge',
            name='code_template',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
