# Generated by Django 5.1.5 on 2025-06-26 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_codechallenge_code_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codechallenge',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
