# Generated by Django 5.1.5 on 2025-06-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_codechallenge_solved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechallenge',
            name='solved_by',
        ),
    ]
