# Generated by Django 5.1.5 on 2025-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_codechallenge_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='completed_challenges',
            field=models.ManyToManyField(blank=True, related_name='solved_by_users', to='core.codechallenge'),
        ),
    ]
